languageCode = "en-us"
title = "scio me nescire"
baseURL = "http://vvuri.ru/"

theme = "hyde"

[params]
  themeColor = "theme-base-08"

#Чем более расширяется область знания, тем шире область незнания